# syntax=docker/dockerfile:1

FROM golang:alpine3.19

RUN apk update && apk add git

RUN go install github.com/beego/bee/v2@latest

RUN export GO111MODULE=on

ENV APP_HOME /go/src/voteparty
RUN mkdir -p "$APP_HOME"
WORKDIR "$APP_HOME"

EXPOSE 8080

CMD ["bee", "run"]
